package com.primapp.utils


enum class ValidationResults {
    EMPTY_EMAIL,
    EMPTY_USERNAME,
    INVALID_USERNAME,
    EMPTY_PASSWORD,
    INVALID_PASSWORD,
    EMPTY_FIRSTNAME,
    EMPTY_LASTNAME,
    EMPTY_GENDER,
    EMPTY_DOB,
    EMPTY_COUNTRY,
    EMPTY_CONFIRM_PASSWORD,
    INVALID_CONFIRM_PASSWORD,
    PASS_NOT_MATCH,
    ERROR_PRIVACY_POLICY,
    EMPTY_FIELD,
    EMAIL_NOT_VALID,
    EMPTY_COMMUNITY_NAME,
    EMPTY_COMMUNITY_DESCRIPTION,
    INVALID_COMMUNITY_NAME_LENGTH,
    INVALID_COMMUNITY_DESCRIPTION_LENGTH,
    SUCCESS,
}